### ISSUE TITLE
Invalid argument supplied for foreach() at line32 in GeoLocation.php

### ISSUE THREAD

**Issue by CLiu13** [LegendOfMCPE/EssentialsPE#221] opened 2016-03-10 15:08 UTC
Title says it all. PHP7

**Comment by markkrueg** [comment] 2016-03-15 00:13
Duplicate of #213 

Please check before posting new issues.

**Comment by CLiu13** [comment] 2016-03-15 00:26
My apologies, didn't read through the issue tracker.

**Closed** 2016-03-15 00:27 UTC
