### ISSUE TITLE
/tpa teleports the other player to you instead of vice versa 

### ISSUE THREAD

**Issue by Skyladd** [LegendOfMCPE/EssentialsPE#234] opened 2016-04-08 23:04 UTC

**Comment by dktapps** [comment] 2016-05-03 18:35
Confirmed this issue with newest commit (still!)

**Comment by Crypthu** [comment] 2016-08-06 19:03
PLEASE FIIIIIIIIIIIIIIIIIIIIIIIIIIX ><

**Comment by Sandertv** [comment] 2016-11-04 21:22
Aware of this problem and looking for a fix.

**Comment by Infernus102** [comment] 2016-11-06 14:00
still not fixed

**Comment by Sandertv** [comment] 2016-11-06 14:01
I know, didn't find out what the problem is yet.

**Comment by Sandertv** [comment] 2016-11-06 16:11
I think I found out... Let me try to test if that is the problem.

**Comment by Sandertv** [comment] 2016-11-14 17:38
It should be fixed. I do not recommend updating yet, I'll test it first.

**Comment by Infernus102** [comment] 2016-11-20 08:56
did you test it?

**Comment by Sandertv** [comment] 2016-11-20 08:59
Yeah it didn't fix it yet. I think I found out what the problem is, I just have to find a clever way to fix it.

**Comment by Sandertv** [comment] 2016-11-20 08:59
You could update though, /tpa works good now, just /tpahere is reversed now.

**Comment by Infernus102** [comment] 2016-11-20 09:21
Why is this so hard? Even experts cant solve this?

**Comment by Sandertv** [comment] 2016-11-20 09:45
The way you get the information whether it is a tphere or tpa request is hard to obtain if you don't know who the sender was when doing /tpaccept. It's saved in a way you need the requester's name to find out what the request was. So I have to find a good way for it.

**Comment by Sandertv** [comment] 2016-11-20 09:48
I think it might in fact work right if you would add the name of the requester in your tpaccept, for example:
/tpaccept steve

**Comment by Infernus102** [comment] 2016-11-20 09:54
But that would be boring

**Comment by Sandertv** [comment] 2016-11-20 09:59
Yep, that's why I still have to find a good way to fix it.

**Comment by Sandertv** [comment] 2016-11-20 11:50
Could you try it with the latest commit? It might work.

**Comment by Infernus102** [comment] 2016-11-20 11:56
i am working on something else, sorry :( will take me some time!

**Comment by Sandertv** [comment] 2016-11-26 08:54
Any results yet @Infernus102 or someone else?

**Comment by Infernus102** [comment] 2016-11-27 11:50
can't confirm, i made my own /tpa and /tpahere

**Comment by Sandertv** [comment] 2016-11-27 11:50
Ah okay, I'll try and check myself.

**Comment by Sandertv** [comment] 2016-11-27 14:20
It seems in fact that it is all working! After like a year of this not working I finally fixed it!

**Comment by Sandertv** [comment] 2016-11-27 14:21
It works as of this commit: 2e5394d2b942193ee694455fdb8fcf6bdcd16b72

**Closed by Sandertv** 2016-11-27 14:21 UTC
Labels: CATEGORY: Bug, STATUS: Confirmed/Reproduced, STATUS: Fixed

**Comment by Infernus102** [comment] 2016-11-27 18:34
**SanderFTW** 👍
