### ISSUE TITLE
Players can't join

### ISSUE THREAD

**Issue by Akuroma** [LegendOfMCPE/EssentialsPE#301] opened 2016-11-09 15:13 UTC
#### Description
Hello. I've got the problem, that players can't join on my server. And I think it's Essential's fault. I've deinstalled it and other people could join. Im using the latest ClearSky-Version as my Server-Jar. I've tried both. An older version of Essentials and the newest one. But everytime it failed. Players who wan't to join my server, are kicked with the console-reason "timeout". But this isn't actually a timeout.
Please help me :( I love this plugin and I want to keep it :(

#### Versions
* EssentialsPE: the newest one
* Game version: W10 0.16

#### Crashdump or console errors

```
```

**Comment by Sandertv** [comment] 2016-11-09 15:20
Hi! Could you tell me what server software you use? It's known to have issues with ClearSky sometimes.

**Comment by Akuroma** [comment] 2016-11-09 15:25
Thank you very much. Could you contact me if it is done? :)

**Comment by Sandertv** [comment] 2016-11-09 15:26
Sure! I'm not 100% sure if I can manage to find out what the issue exactly is, but I'll try my best.

**Comment by Akuroma** [comment] 2016-11-09 15:29
This is nice of you ;) Thank you very much :D

**Comment by Sandertv** [comment] 2016-11-15 11:06
It seems that PMMP users seem to experience this issue too. Could anyone try to reproduce this isue with PMMP?

**Comment by Sandertv** [comment] 2016-11-15 15:05
@Akuroma the latest version might have fixed it, try it out.

**Comment by Akuroma** [comment] 2016-11-15 15:09
I'll try it.

**Comment by Akuroma** [comment] 2016-11-15 15:14
Still doesn't work with ClearSky 0.16

**Comment by Sandertv** [comment] 2016-11-15 15:15
Dang...

**Comment by Sandertv** [comment] 2016-12-05 06:36
I'm afraid I really can't do anything about this.

**Comment by SOF3** [comment] 2016-12-05 11:32
ClearSky should not be supported by EssentialsPE...

**Comment by Sandertv** [comment] 2016-12-05 12:01
@SOF3 I'm not planning to do any behaviour changing things to get just ClearSky working. I myself of course always go for PM support, but I'm going to be standing aside from this and add support for every PM based software possible if it doesn't change the behaviour of it on PM. (and if I find out what is the issue at all)

**Comment by Sandertv** [comment] 2016-12-05 12:02
Too many people use PocketMine spoons right now to not support those.

**Comment by SOF3** [comment] 2016-12-05 12:46
@Sandertv good luck. I hope that by the time you finish them, the spoons have not all died away yet :)

**Comment by Sandertv** [comment] 2016-12-05 12:47
Stress the world possible. ^^

**Comment by HimbeersaftLP** [comment] 2016-12-05 13:51
> @Sandertv good luck. I hope that by the time you finish them, the spoons have not all died away yet :)

**yet** :P

**Comment by jasonwynn10** [comment] 2016-12-11 01:53
THE ISSUE IS WITH NICKNAMES!!! Delete the players nicknames in their configs!

**Comment by Sandertv** [comment] 2016-12-11 07:10
That's odd... Thanks a hell of a lot for telling us @jasonwynn10, I'll see if I can fix it.

**Comment by EradiaPE** [comment] 2016-12-13 22:46
Please update :(

**Comment by Sandertv** [comment] 2016-12-14 06:23
It should work just fine...

**Comment by jasonwynn10** [comment] 2016-12-14 16:05
This issue occurs on my server too. When I looked at those players configs, only the nicknames looked out of place

**Comment by Sandertv** [comment] 2016-12-14 16:12
Do use ClearSky @jasonwynn10 ?

**Comment by jasonwynn10** [comment] 2016-12-14 18:41
I use pmmp PocketMine

**Comment by Sandertv** [comment] 2016-12-14 19:01
Hmmm... When I tested this on PocketMine it worked just fine. That's odd.

**Comment by Sandertv** [comment] 2016-12-25 23:18
Okay well just debugged and it doesn't matter if the nick is coloured or not, it just doesn't allow to enter at all if you have any nick... Hmmm...

**Comment by Sandertv** [comment] 2016-12-26 21:17
Fixed as of 746d7e16c24ff0e698ca5031f50799f99f4f19ce

**Closed by Sandertv** 2016-12-26 21:17 UTC
Labels: CATEGORY: Bug, CATEGORY: Server Software Issue, STATUS: Confirmed/Reproduced, STATUS: Work In Progress
