### ISSUE TITLE
/tpa Bug

### ISSUE THREAD

**Issue by AndreySK4** [LegendOfMCPE/EssentialsPE#211] opened 2016-02-23 16:54 UTC
I have a problem./tpa not works.do the same thing as /tpahere

**Comment by Tolo0** [comment] 2016-02-23 17:01
Lol that's a weird bug. Are u using some other plugin that has tp commands?

**Comment by AndreyR0** [comment] 2016-02-23 17:35
No

**Comment by Tolo0** [comment] 2016-02-23 17:37
What version of EssentialsPE are u using? What pocketmine.phar version php5 or 7? Maybe show ur plugins. One could be conflicting with it.

**Comment by AndreyR0** [comment] 2016-02-23 19:13
I  use EssentialsPE 2.0.0 and Genisys 1.1 PHP7

**Comment by Tolo0** [comment] 2016-02-23 20:11
Try this version. 

[EssentialsPE-edit.phar.zip](https://github.com/LegendOfMCPE/EssentialsPE/files/143325/EssentialsPE-edit.phar.zip)

**Comment by Aericio** [comment] 2016-02-25 07:54
Oh. Im having that same bug. Does that edited phar work?

**Comment by PEMapModder** [comment] 2016-02-25 08:27
@Tolo0 please, if you have fixes, create pull request rather than redistributing phar files of custom edits.

**Comment by Tolo0** [comment] 2016-02-25 08:30
Sorry PEMapModder won't happen again.

**Comment by Aericio** [comment] 2016-02-27 02:16
Wait... The file is just an old version of EssentialsPE though...
![image](https://cloud.githubusercontent.com/assets/16523741/13370166/4c4ff0ba-dca4-11e5-9978-483e6cb7d223.png)
So its not really a fix? Just an older version? (unless he edited the older version)

**Comment by iksaku** [comment] 2016-03-22 21:59
Could somebody confirm that this bug is present in latest `Development0 builds?`

**Comment by LordJoshie** [comment] 2016-04-14 11:26
Wait. what 'edited phar'  I also use Genisys & have the same TPA issue

**Comment by Aericio** [comment] 2016-04-15 01:40
Im pretty sure the "edited phar" is literally an older version of essentials.

**Comment by Sandertv** [comment] 2016-11-04 21:24
Duplicate of other issues.

**Closed** 2016-11-04 21:25 UTC
Labels: Bug, Not Confirmed
