### ISSUE TITLE
Join and Leave Messages showing {%0} Instead of Player Name

### ISSUE THREAD

**Issue by markkrueg** [LegendOfMCPE/EssentialsPE#93] opened 2015-06-03 07:56 UTC
This issue is definitely still there. I did a clean install of PocketMineMP 1199 with the ONLY plugin being EssentialsPE v1.1.0 Beta 7. All I did was start it up and select the defaults in the PocketMineMP setup wizard. When I joined the server I see:

07:45:47 [INFO] {%0} joined the game
07:46:08 [INFO] {%0} left the game

![screenshot_2015-06-03-00-45-52](https://cloud.githubusercontent.com/assets/12489897/7955158/de4f4526-098a-11e5-9a8b-1b52109ab890.png)

![screen shot 2015-06-03 at 12 54 36 am](https://cloud.githubusercontent.com/assets/12489897/7955207/35f7c19a-098b-11e5-8f3c-242e9716c70b.png)

**Comment by matcracker** [comment] 2015-06-03 13:19
I can confirm!

**Comment by iksaku** [comment] 2015-06-03 15:59
This issue has been fixed in the development version, we're just waiting for some tests to be finished to release a new Beta Build 8 ;)

**Closed by iksaku** 2015-06-03 15:59 UTC

**Comment by thebigsmileXD** [comment] 2015-07-18 06:58
This definitely is back there.. Why dont you add an option to choose if you want a join/leave message or not?
Because i have another plugins doing the join messages and its really annoying

**Comment by iksaku** [comment] 2015-07-18 07:20
If we add option to change messages, it will conflict with other plugins, also, we don't set the message directly, we just replace the "real name" with the "nick" and that's it, everything else should be okey

**Comment by thebigsmileXD** [comment] 2015-08-01 11:46
Actually, the new version of the Plugin on GitHub works just perfectly. I did alot testing and still found zero bugs or problems, also with almost 60 plugins installed there are no conflicts or whatsoever. I guess you should update the one on the pocketmine Forums.
Thank you for working hard on a plugin like that!
