### ISSUE TITLE
I seriously can't gamemode people. Don't close this issue. ITS NOT FIXED

### ISSUE THREAD

**Issue by Lucario2** [LegendOfMCPE/EssentialsPE#154] opened 2015-08-16 17:00 UTC

**Comment by Lucario2** [comment] 2015-08-16 17:00
i really CAN'T GAMEMODE PEOPLE

**Comment by Lucario2** [comment] 2015-08-16 17:04
I'll try to make a video

**Comment by DinoKill** [comment] 2015-08-16 17:14
You'll have to give more info then that if you want help... "I REALLY CANT GAMEMODE" doesn't really tell us much. What happens when you do? Is there any crash report?

**Comment by Lucario2** [comment] 2015-08-16 17:14
No.

**Comment by Lucario2** [comment] 2015-08-16 17:14
It just says you don't have permission to this this or something

**Comment by Lucario2** [comment] 2015-08-16 17:15
It's a huge problem for me. I need to gamemode my players and admin what do I do?

**Comment by LDX-MCPE** [comment] 2015-08-16 18:17
This is a duplicate of #149. Please stop opening duplicate issues, or we will be forced to block you from the EssentialsPE repository.

**Closed by LDX-MCPE** 2015-08-16 18:17 UTC

**Comment by DinoKill** [comment] 2015-08-17 08:11
This is not our problem this is a problem with your permission setup.

**Comment by 64FF00** [comment] 2015-08-17 11:34
@Lucario2 https://github.com/LegendOfMCPE/EssentialsPE/wiki/Permission-Nodes
