### ISSUE TITLE
FIX THE TPA ALREADY. IT SHOULD BE A PRIORITY.

### ISSUE THREAD

**Issue by LordJoshie** [LegendOfMCPE/EssentialsPE#239] opened 2016-04-14 00:24 UTC
Yeaaaah........ TPA & TPAHERE ARE THE SAME FUNCTION. 

not cool. 

Fix plz. <3 

I tried adding the file, but couldn't figure it out.

**Comment by PEMapModder** [comment] 2016-04-14 09:27
> not cool = it's hot

**Comment by LordJoshie** [comment] 2016-04-14 09:28
looool.
c'mon, I neeeeeeeeeed this !!

checkout play.purecraftpe.ca 19132

I need tpa to function properly <3

**Comment by LordJoshie** [comment] 2016-04-14 09:42
Could you tell me what this is my friend?

These errors come up a lot. but not always.

What's it from do ya think?

It's nasty :/

**Comment by PEMapModder** [comment] 2016-04-14 11:23
Lack of explanation. Possible duplicate of #228 #211 #234

**Closed by PEMapModder** 2016-04-14 11:23 UTC

**Comment by LordJoshie** [comment] 2016-04-14 11:25
:( I have no idea what that means. & I wish I did.
could you maybe help me ?
I also use HereAuth.

Are you going to add the tpa feature to work as it should ?

pretty pretty please. with cherries on top !

**Comment by PEMapModder** [comment] 2016-04-14 11:26
This is not a forum. Please don't use this for asking questions. This issue tracker is only for tracking issues.
