### ISSUE TITLE
Bug with 0.14.2 (protocol 60) and EssentialsPE 2.0.0 getId

### ISSUE THREAD

**Issue by ZizzyZizzy** [LegendOfMCPE/EssentialsPE#249] opened 2016-04-28 05:06 UTC
27.04 23:02:44 [Server] Server thread/CRITICAL Error: "Call to a member function getId() on array" (EXCEPTION) in "/EssentialsPE.phar/src/EssentialsPE/BaseFiles/BaseAPI" at line 1656

Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'EssentialsPE v2.0.0': Call to a member function getId() on array on EssentialsPE\EventHandlers\PlayerEvents

**Comment by iksaku** [comment] 2016-04-28 15:46
Duplicate of #248

**Closed by iksaku** 2016-04-28 15:46 UTC
Labels: Duplicated Issue
